### ISSUE TITLE
performance and ecc

### ISSUE THREAD

**Issue by Sicaine** [hughobrien/zfs-remote-mirror#1]
Hey,

do you have any data how long it takes to scrub 1tb on a raspberrypi?

Besides that: You shouldn't use zfs without ecc. ZFS is not protected without and you can scrub your backups to death.

**Comment by hughobrien** [comment]
Hey there,

Holy smokes, I didn't realise that. I'll add some sections on memory testing and recommend ECC memory (though that makes the 'home use' avenue trickier). Thank you.

I'll soon find out how long a scrub takes on a RPi (and then caution against doing it), and will post back with the results.

To any other readers: Sicaine is saying that if a bad DIMM causes ZFS's checksum testing to think there's an error on the disk, but in fact it's really the memory, it will presume the memory is good and modify the disk, thus corrupting the otherwise good data. This happens on every read, so when scrubbing, we expose the entire disk to a bad DIMM. Bad news indeed.

**Comment by hughobrien** [comment]
Seems like the need for ECC memory is something of a hot debate in the ZFS community, so I've added an appendix giving a brief overview.
